set hlsearch incsearch
set wildmenu
set number
set autoindent
set smarttab            " make tab insert indedents instead of tabs at beginning fo a line
set expandtab           " set expandtab
set laststatus=2
set sts=4
set ts=1
set sw=4

silent execute '!mkdir -p $HOME/.vim/tmp/backup'
set backupdir=$HOME/.vim/tmp/backup " where to store backup
silent execute '!mkdir -p $HOME/.vim/tmp/swap'
set directory=$HOME/.vim/tmp/swap "where to store swap
silent execute '!mkdir -p $HOME/.vim/tmp/views'
set viewdir=$HOME/.vim/tmp/views " where to store view
silent execute '!mkdir -p $HOME/.vim/tmp/undo'
set undodir=$HOME/.vim/tmp/undo " where to store undo</undofile></backup>


syntax on

filetype on
filetype indent on

set statusline+=%#warningmsg#
set statusline+=%*
